import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans, JetBrains_Mono } from "next/font/google";
import Cursor from "@/components/Cursor";

export const dmSans = DM_Sans({ subsets: ["latin"] });
export const jetBrainsMono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.className} antialiased font-bold overflow-clip bg-[#e2e2d1]`}
      >
        <Cursor />
        <svg className="pointer-events-none absolute cursor-none">
          <filter id="grainy">
            <feTurbulence type="turbulence" baseFrequency="0.5"></feTurbulence>
            <feColorMatrix type="saturate" values="0"></feColorMatrix>
          </filter>
        </svg>
        {children}
      </body>
    </html>
  );
}
