import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import Cursor from "@/components/Cursor";
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased font-bold overflow-x-clip text-white bg-tan`}
      >
        <Cursor />
        <svg className="pointer-events-none absolute cursor-none">
          <filter id="grainy">
            <feTurbulence type="turbulence" baseFrequency="0.5"></feTurbulence>
            <feColorMatrix type="saturate" values="0"></feColorMatrix>
          </filter>
        </svg>
        {children}
      </body>
    </html>
  );
}
